rd /s /q packages
rd /s /q BasePageObjectModel\bin
rd /s /q BasePageObjectModel\obj
rd /s /q BasePageObjectModel.MSTest\bin
rd /s /q BasePageObjectModel.MSTest\obj
rd /s /q BasePageObjectModel.Nunit\bin
rd /s /q BasePageObjectModel.Nunit\obj
rd /s /q BasePageObjectModel.Tests\bin
rd /s /q BasePageObjectModel.Tests\obj
rd /s /q BasePageObjectModel.xUnit\bin
rd /s /q BasePageObjectModel.xUnit\obj
rd /s /q TestApp\bin
rd /s /q TestApp\obj
rd /s /q TestPageObjectModel\bin
rd /s /q TestPageObjectModel\obj
rd /s /q TestSpecs\bin
rd /s /q TestSpecs\obj
