// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TestSpecs
{
	using TechTalk.SpecFlow;


	[System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
	[System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	[NUnit.Framework.TestFixtureAttribute()]
	[NUnit.Framework.DescriptionAttribute("HomePage")]
	public partial class HomePageFeature
	{

		private TechTalk.SpecFlow.ITestRunner testRunner;

#line 1 "HomePage.feature"
#line hidden

		[NUnit.Framework.OneTimeSetUp()]
		public virtual void FeatureSetup()
		{
			testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
			TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "HomePage", null, ProgrammingLanguage.CSharp, ((string[])(null)));
			testRunner.OnFeatureStart(featureInfo);
		}

		[NUnit.Framework.OneTimeTearDown()]
		public virtual void FeatureTearDown()
		{
			testRunner.OnFeatureEnd();
			testRunner = null;
		}

		[NUnit.Framework.SetUpAttribute()]
		public virtual void TestInitialize()
		{
		}

		[NUnit.Framework.TearDownAttribute()]
		public virtual void ScenarioTearDown()
		{
			testRunner.OnScenarioEnd();
		}

		public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
		{
			testRunner.OnScenarioStart(scenarioInfo);
		}

		public virtual void ScenarioCleanup()
		{
			testRunner.CollectScenarioErrors();
		}

		[NUnit.Framework.TestAttribute()]
		[NUnit.Framework.DescriptionAttribute("The title on the home page is showing")]
		public virtual void TheTitleOnTheHomePageIsShowing()
		{
			TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The title on the home page is showing", ((string[])(null)));
#line 3
			this.ScenarioSetup(scenarioInfo);
#line 4
			testRunner.Given("I am on the home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 5
			testRunner.Then("the title should be showing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
			this.ScenarioCleanup();
		}

		[NUnit.Framework.TestAttribute()]
		[NUnit.Framework.DescriptionAttribute("Navigating from the home page to the second page")]
		public virtual void NavigatingFromTheHomePageToTheSecondPage()
		{
			TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Navigating from the home page to the second page", ((string[])(null)));
#line 7
			this.ScenarioSetup(scenarioInfo);
#line 8
			testRunner.Given("I am on the home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 9
			testRunner.When("I click on the second page link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 10
			testRunner.Then("I should be on the second page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
			this.ScenarioCleanup();
		}

		[NUnit.Framework.TestAttribute()]
		[NUnit.Framework.DescriptionAttribute("Create the something else")]
		public virtual void CreateTheSomethingElse()
		{
			TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create the something else", ((string[])(null)));
#line 12
			this.ScenarioSetup(scenarioInfo);
#line 13
			testRunner.Given("I am on the create page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
			TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
						"Label",
						"Value"});
			table1.AddRow(new string[] {
						"FullName",
						"Scott Reed"});
			table1.AddRow(new string[] {
						"FullAddress",
						"3350 Brennan Dr, Raleigh NC, 27613"});
#line 14
			testRunner.When("I fill out the form with all kinds of characters", ((string)(null)), table1, "When ");
#line 18
			testRunner.And("I click Create", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 19
			testRunner.Then("I should see the new value in the list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
			this.ScenarioCleanup();
		}
	}
}
#pragma warning restore
#endregion
